// One-shot local environment bootstrap (idempotent). Run after `pnpm local:up`:
//   pnpm local:bootstrap
//
// Creates the DynamoDB table on LocalStack and a Cognito user pool + app client
// + a ready-to-use dev user on cognito-local, then writes local-config.json and
// .env.local so the app and local API server are wired up.

import { writeFileSync } from 'node:fs';
import {
  CreateTableCommand,
  DescribeTableCommand,
  DynamoDBClient,
  ResourceNotFoundException,
} from '@aws-sdk/client-dynamodb';
import {
  AdminCreateUserCommand,
  AdminSetUserPasswordCommand,
  CognitoIdentityProviderClient,
  CreateUserPoolClientCommand,
  CreateUserPoolCommand,
  ListUserPoolClientsCommand,
  ListUserPoolsCommand,
} from '@aws-sdk/client-cognito-identity-provider';
import { UPDATED_AT_INDEX } from '../sync/dynamoStore';
import { ENV_LOCAL_PATH, LOCAL, writeLocalConfig, type LocalConfig } from './config';

const creds = { accessKeyId: 'test', secretAccessKey: 'test' };

async function ensureTable(): Promise<void> {
  const ddb = new DynamoDBClient({
    region: LOCAL.region,
    endpoint: LOCAL.ddbEndpoint,
    credentials: creds,
  });
  try {
    await ddb.send(new DescribeTableCommand({ TableName: LOCAL.tableName }));
    console.log(`✓ DynamoDB table "${LOCAL.tableName}" already exists`);
    return;
  } catch (err) {
    if (!(err instanceof ResourceNotFoundException)) throw err;
  }
  await ddb.send(
    new CreateTableCommand({
      TableName: LOCAL.tableName,
      BillingMode: 'PAY_PER_REQUEST',
      AttributeDefinitions: [
        { AttributeName: 'userId', AttributeType: 'S' },
        { AttributeName: 'id', AttributeType: 'S' },
        { AttributeName: 'updatedAt', AttributeType: 'N' },
      ],
      KeySchema: [
        { AttributeName: 'userId', KeyType: 'HASH' },
        { AttributeName: 'id', KeyType: 'RANGE' },
      ],
      GlobalSecondaryIndexes: [
        {
          IndexName: UPDATED_AT_INDEX,
          KeySchema: [
            { AttributeName: 'userId', KeyType: 'HASH' },
            { AttributeName: 'updatedAt', KeyType: 'RANGE' },
          ],
          Projection: { ProjectionType: 'ALL' },
        },
      ],
    }),
  );
  console.log(`✓ Created DynamoDB table "${LOCAL.tableName}"`);
}

async function ensurePool(): Promise<{ userPoolId: string; clientId: string }> {
  const idp = new CognitoIdentityProviderClient({
    region: LOCAL.region,
    endpoint: LOCAL.cognitoEndpoint,
    credentials: creds,
  });

  const pools = await idp.send(new ListUserPoolsCommand({ MaxResults: 60 }));
  let userPoolId = pools.UserPools?.find((p) => p.Name === LOCAL.userPoolName)?.Id;
  if (!userPoolId) {
    const created = await idp.send(
      new CreateUserPoolCommand({
        PoolName: LOCAL.userPoolName,
        UsernameAttributes: ['email'],
        AutoVerifiedAttributes: ['email'],
      }),
    );
    userPoolId = created.UserPool?.Id;
    if (!userPoolId) throw new Error('cognito-local did not return a user pool id');
    console.log(`✓ Created user pool ${userPoolId}`);
  } else {
    console.log(`✓ User pool ${userPoolId} already exists`);
  }

  const clients = await idp.send(
    new ListUserPoolClientsCommand({ UserPoolId: userPoolId, MaxResults: 60 }),
  );
  let clientId = clients.UserPoolClients?.find(
    (c) => c.ClientName === LOCAL.appClientName,
  )?.ClientId;
  if (!clientId) {
    const created = await idp.send(
      new CreateUserPoolClientCommand({
        UserPoolId: userPoolId,
        ClientName: LOCAL.appClientName,
        GenerateSecret: false,
        ExplicitAuthFlows: ['ALLOW_USER_PASSWORD_AUTH', 'ALLOW_REFRESH_TOKEN_AUTH'],
      }),
    );
    clientId = created.UserPoolClient?.ClientId;
    if (!clientId) throw new Error('cognito-local did not return an app client id');
    console.log(`✓ Created app client ${clientId}`);
  } else {
    console.log(`✓ App client ${clientId} already exists`);
  }

  // Ensure a ready dev user (confirmed, permanent password).
  try {
    await idp.send(
      new AdminCreateUserCommand({
        UserPoolId: userPoolId,
        Username: LOCAL.devUser.email,
        UserAttributes: [
          { Name: 'email', Value: LOCAL.devUser.email },
          { Name: 'email_verified', Value: 'true' },
        ],
        MessageAction: 'SUPPRESS',
      }),
    );
    console.log(`✓ Created dev user ${LOCAL.devUser.email}`);
  } catch (err) {
    if ((err as { name?: string }).name !== 'UsernameExistsException') throw err;
    console.log(`✓ Dev user ${LOCAL.devUser.email} already exists`);
  }
  await idp.send(
    new AdminSetUserPasswordCommand({
      UserPoolId: userPoolId,
      Username: LOCAL.devUser.email,
      Password: LOCAL.devUser.password,
      Permanent: true,
    }),
  );

  return { userPoolId, clientId };
}

function writeEnvLocal(cfg: LocalConfig): void {
  const lines = [
    '# Generated by `pnpm local:bootstrap` — local dev only, do not commit.',
    `VITE_API_BASE_URL=http://localhost:${cfg.apiPort}`,
    `VITE_COGNITO_USER_POOL_ID=${cfg.userPoolId}`,
    `VITE_COGNITO_CLIENT_ID=${cfg.clientId}`,
    `VITE_COGNITO_ENDPOINT=${cfg.cognitoEndpoint}`,
    `VITE_COGNITO_REGION=${cfg.region}`,
    '',
  ];
  writeFileSync(ENV_LOCAL_PATH, lines.join('\n'));
}

async function main(): Promise<void> {
  console.log('Bootstrapping local SteadyDose environment…');
  await ensureTable();
  const { userPoolId, clientId } = await ensurePool();

  const cfg: LocalConfig = {
    userPoolId,
    clientId,
    issuer: `${LOCAL.cognitoEndpoint}/${userPoolId}`,
    tableName: LOCAL.tableName,
    region: LOCAL.region,
    ddbEndpoint: LOCAL.ddbEndpoint,
    cognitoEndpoint: LOCAL.cognitoEndpoint,
    apiPort: LOCAL.apiPort,
  };
  writeLocalConfig(cfg);
  writeEnvLocal(cfg);

  console.log('\nDone. Next:');
  console.log('  pnpm local:api    # start the local sync API');
  console.log('  pnpm dev          # start the app (reads .env.local)');
  console.log(`  Sign in with ${LOCAL.devUser.email} / ${LOCAL.devUser.password}`);
}

main().catch((err) => {
  console.error('\nBootstrap failed:', err);
  process.exitCode = 1;
});
