#!/usr/bin/env node
// The fallow audit, run with the agent tooling's coverage attached.
//
//   pnpm agent:audit                 # against the branch's upstream/merge-base
//   pnpm agent:audit --base main     # against an explicit ref
//
// Why this exists rather than a bare `fallow audit` in CI:
//
//   1. `fallow audit` ignores the config's `health.coverage` — only `--coverage`
//      / `FALLOW_COVERAGE` reach it. Nothing warns you; the audit just scores
//      `scripts/agent/**` as if it had no tests, and its CLI functions come back
//      as critical CRAP risks.
//   2. Coverage that is absent *or stale* fails the same silent way. A report
//      generated before a source edit has the wrong line offsets, so fallow
//      cannot match functions to it and quietly falls back to estimation — which
//      is how a green local run turns into a red CI one for no visible reason.
//
// So both cases are hard errors here. An audit that cannot see the coverage it
// depends on is not a passing audit, it is an unmeasured one.

import { existsSync, readdirSync, statSync } from 'node:fs';
import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const coveragePath = join(root, 'coverage/agent/coverage-final.json');
const sourceDir = join(root, 'scripts/agent');

const argv = process.argv.slice(2);
const baseIndex = argv.indexOf('--base');
const base = baseIndex === -1 ? null : argv[baseIndex + 1];

function die(lines) {
  console.error(lines.join('\n'));
  process.exit(1);
}

if (!existsSync(coveragePath)) {
  die([
    `agent-audit: no coverage at ${coveragePath}`,
    'Run `pnpm agent:test:coverage` first. Auditing without it scores every',
    'branchy CLI function in scripts/agent/ as a critical risk.',
  ]);
}

// Staleness: any tracked source newer than the report means the report's line
// offsets no longer describe the code fallow is about to read. Only `.mjs`
// sources matter — the report is regenerated by running the tests, so test
// edits are already reflected in it.
const coverageMtime = statSync(coveragePath).mtimeMs;
const newer = readdirSync(sourceDir, { recursive: true, withFileTypes: true })
  .filter((e) => e.isFile() && e.name.endsWith('.mjs') && !e.parentPath.includes('__tests__'))
  .map((e) => join(e.parentPath, e.name))
  .filter((path) => statSync(path).mtimeMs > coverageMtime)
  .map((path) => path.slice(root.length + 1));

if (newer.length) {
  die([
    'agent-audit: the coverage report is older than the code it describes:',
    ...newer.map((p) => `  ${p}`),
    '',
    'Re-run `pnpm agent:test:coverage`. Stale offsets stop fallow matching',
    'functions to coverage, so it silently falls back to estimation.',
  ]);
}

const result = spawnSync(
  join(root, 'node_modules/.bin/fallow'),
  ['audit', ...(base ? ['--base', base] : []), '--format', 'markdown'],
  { stdio: 'inherit', env: { ...process.env, FALLOW_COVERAGE: coveragePath } },
);

process.exit(result.status ?? 1);
