#!/usr/bin/env node
// Write .env.local from the running local Supabase stack, so the Vite app picks
// up the local API URL + anon key. Run after `supabase start`:
//
//   pnpm local:env
//
// This replaces the old `pnpm local:bootstrap` env generation. Only the
// publishable anon key is written (RLS protects data); the service-role key is
// never put in client env.

import { execFileSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');

let raw;
try {
  raw = execFileSync('supabase', ['status', '-o', 'env'], { encoding: 'utf8' });
} catch {
  console.error('Could not read `supabase status`. Run `supabase start` first.');
  process.exit(1);
}

// `supabase status -o env` prints KEY="value" lines.
const env = Object.fromEntries(
  raw
    .split('\n')
    .map((line) => line.match(/^([A-Z0-9_]+)="?(.*?)"?$/))
    .filter(Boolean)
    .map((m) => [m[1], m[2]]),
);

const url = env.API_URL;
const anonKey = env.ANON_KEY;
if (!url || !anonKey) {
  console.error('Missing API_URL / ANON_KEY in `supabase status` output.');
  process.exit(1);
}

const contents = [
  '# Generated by `pnpm local:env` — local dev only, do not commit.',
  `VITE_SUPABASE_URL=${url}`,
  `VITE_SUPABASE_ANON_KEY=${anonKey}`,
  '',
].join('\n');

writeFileSync(join(root, '.env.local'), contents);
console.log(
  'Wrote .env.local for local Supabase. Sign in with dev@steadydose.local / DevPassw0rd!',
);
